backend:
  name: git-gateway
  branch: netlify-cms # Branch to update (optional; defaults to master)
media_folder: "docs/.vuepress/public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "sutta" # Used in routes, e.g., /admin/collections/blog
    label: "Sutta" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: slug
    path: "{{slug}}/index" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Page Class", name: "pageClass", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }